train_pkl: ${DATA_ROOT}/ihm/train_p2x_data.pkl
val_pkl: ${DATA_ROOT}/ihm/val_p2x_data.pkl
test_pkl: ${DATA_ROOT}/ihm/test_p2x_data.pkl

save_path: models/ihm_cnn

max_seq_len: 0
batch_size: 8
num_epochs: 30
lr: 5e-4
weight_decay: 0.0
warmup_ratio: 0.0
grad_accum: 1
pretrained_meta_model: null
use_4bit: false
lora: null
num_filters: 64
kernel_size: 3
dropout: 0.1
model_type: cnn
task: ihm
num_labels: 1
wandb: true
mixed_precision: "no"
