train_pkl: ${DATA_ROOT}/pheno/train_p2x_data.pkl
val_pkl: ${DATA_ROOT}/pheno/val_p2x_data.pkl
test_pkl: ${DATA_ROOT}/pheno/test_p2x_data.pkl

save_path: models/pheno_clinical_bigbird

max_seq_len: 256
batch_size: 8
num_epochs: 1
lr: 8e-6
weight_decay: 0.01
warmup_ratio: 0.1
grad_accum: 2
pretrained_meta_model: hf-internal-testing/tiny-random-BigBirdForSequenceClassification
use_4bit: false
lora:
    null
model_type: clinicalbigbird
pooling: cls
task: pheno
num_labels: 25
wandb: false
mixed_precision: "bf16"
