train_pkl: ${DATA_ROOT}/pheno_train.pkl
val_pkl: ${DATA_ROOT}/pheno_val.pkl
test_pkl: ${DATA_ROOT}/pheno_test.pkl

save_path: pheno_model

max_seq_len: 4096
batch_size: 4
num_epochs: 5
lr: 2e-5
weight_decay: 0.01
warmup_ratio: 0.1
grad_accum: 1
pretrained_meta_model: meta-llama/Meta-Llama-3-8B-Instruct
use_4bit: true
lora:
  r: 8
  alpha: 32
  dropout: 0.05
task: pheno
num_labels: 25
wandb: true
