train_pkl: ${DATA_ROOT}/pheno/train_p2x_data.pkl
val_pkl: ${DATA_ROOT}/pheno/val_p2x_data.pkl
test_pkl: ${DATA_ROOT}/pheno/test_p2x_data.pkl

save_path: models/pheno_model

max_seq_len: 6000
batch_size: 4
num_epochs: 5
lr: 2e-5
weight_decay: 0.01
warmup_ratio: 0.1
grad_accum: 2
pretrained_meta_model: meta-llama/Meta-Llama-3-8B-Instruct
use_4bit: true
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
task: pheno
num_labels: 25
wandb: true
mixed_precision: "bf16"  # 可选: "no", "fp16", "bf16"
