train_pkl: ${DATA_ROOT}/pheno/train_p2x_data.pkl
val_pkl: ${DATA_ROOT}/pheno/val_p2x_data.pkl
test_pkl: ${DATA_ROOT}/pheno/test_p2x_data.pkl

save_path: models/pheno_lstm

max_seq_len: 0
batch_size: 8
num_epochs: 3
lr: 1e-3
weight_decay: 0.0
warmup_ratio: 0.0
grad_accum: 1
pretrained_meta_model: null
use_4bit: false
lora: null
hidden_dim: 128
num_layers: 3
dropout: 0.1
model_type: lstm
task: pheno
num_labels: 25
wandb: false
mixed_precision: "no"
