_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
                - 71
                - 98
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.52.4
            "8":
                - 5
            "12": 0.19.11
            "13": linux-aarch64
batch_size:
    value: 2
grad_accum:
    value: 1
lora:
    value:
        lora_alpha: 32
        lora_dropout: 0.05
        r: 16
lr:
    value: 2e-05
max_seq_len:
    value: 6000
mixed_precision:
    value: bf16
num_epochs:
    value: 5
num_labels:
    value: 25
pretrained_meta_model:
    value: meta-llama/Meta-Llama-3-8B-Instruct
save_path:
    value: models/pheno_model
task:
    value: pheno
test_pkl:
    value: /home/ubuntu/hcy50662/output_mimic3/pheno/test_p2x_data.pkl
train_pkl:
    value: /home/ubuntu/hcy50662/output_mimic3/pheno/train_p2x_data.pkl
use_4bit:
    value: true
val_pkl:
    value: /home/ubuntu/hcy50662/output_mimic3/pheno/val_p2x_data.pkl
wandb:
    value: true
warmup_ratio:
    value: 0.1
weight_decay:
    value: 0.01
