_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 71
                - 98
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 71
                - 98
            "3":
                - 16
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": linux-aarch64
batch_size:
    value: 4
grad_accum:
    value: 2
lora:
    value:
        bias: none
        lora_alpha: 16
        lora_dropout: 0.05
        r: 8
        target_modules:
            - query
            - key
            - value
        task_type: SEQ_CLS
lr:
    value: 2e-05
max_seq_len:
    value: 4096
mixed_precision:
    value: bf16
model_type:
    value: clinicallongformer
num_epochs:
    value: 5
num_labels:
    value: 25
pooling:
    value: cls
pretrained_meta_model:
    value: yikuan8/Clinical-Longformer
save_path:
    value: models/pheno_clinical_longformer
task:
    value: pheno
test_pkl:
    value: /home/ubuntu/hcy50662/output_mimic3/pheno/test_p2x_data.pkl
train_pkl:
    value: /home/ubuntu/hcy50662/output_mimic3/pheno/train_p2x_data.pkl
use_4bit:
    value: false
val_pkl:
    value: /home/ubuntu/hcy50662/output_mimic3/pheno/val_p2x_data.pkl
wandb:
    value: true
warmup_ratio:
    value: 0.1
weight_decay:
    value: 0.01
